/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: The Hallwyl Museum (Hallwylska museet) (https://sketchfab.com/TheHallwylMuseum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-picture-gallery-231fdb3e9e354c6faaa3c250f8c9988f
Title: The Picture Gallery
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-1, -2.9, -2.057]}
        rotation={[3.136, 0, 0.012]}
        scale={0.5}
      >
        <group position={[-6.02, -7.155, -12.624]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials["161122_HWY_Galleri_Material_u1_v1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
